import React from 'react';
import {
  SquaresFour,
  Percent,
  ChartBar,
  Receipt,
  Wallet,
  Plus,
  Trash,
  CalendarBlank,
  MagnifyingGlass,
  ArrowUpRight,
  ArrowDownLeft,
  Sparkle,
  X,
  List,
  Coins,
  Copy,
  CaretLeft,
  CaretRight,
  SidebarSimple,
  ChartPie,
  Sun,
  Moon
} from '@phosphor-icons/react';

export const Icons = {
  Dashboard: ({ className = "w-5 h-5" }: { className?: string }) => <SquaresFour className={className} weight="duotone" />,
  Percent: ({ className = "w-5 h-5" }: { className?: string }) => <Percent className={className} weight="bold" />,
  ChartBar: ({ className = "w-5 h-5" }: { className?: string }) => <ChartBar className={className} weight="duotone" />,
  BarChart: ({ className = "w-5 h-5" }: { className?: string }) => <ChartBar className={className} weight="duotone" />,
  Receipt: ({ className = "w-5 h-5" }: { className?: string }) => <Receipt className={className} weight="duotone" />,
  Wallet: ({ className = "w-5 h-5" }: { className?: string }) => <Wallet className={className} weight="duotone" />,
  Plus: ({ className = "w-5 h-5" }: { className?: string }) => <Plus className={className} weight="bold" />,
  Trash: ({ className = "w-4 h-4" }: { className?: string }) => <Trash className={className} weight="duotone" />,
  Calendar: ({ className = "w-4 h-4" }: { className?: string }) => <CalendarBlank className={className} weight="duotone" />,
  Search: ({ className = "w-4 h-4" }: { className?: string }) => <MagnifyingGlass className={className} weight="bold" />,
  ArrowUpRight: ({ className = "w-4 h-4" }: { className?: string }) => <ArrowUpRight className={className} weight="bold" />,
  ArrowDownLeft: ({ className = "w-4 h-4" }: { className?: string }) => <ArrowDownLeft className={className} weight="bold" />,
  Sparkles: ({ className = "w-5 h-5" }: { className?: string }) => <Sparkle className={className} weight="fill" />,
  X: ({ className = "w-5 h-5" }: { className?: string }) => <X className={className} weight="bold" />,
  Menu: ({ className = "w-6 h-6" }: { className?: string }) => <List className={className} weight="bold" />,
  Coins: ({ className = "w-5 h-5" }: { className?: string }) => <Coins className={className} weight="duotone" />,
  Copy: ({ className = "w-4 h-4" }: { className?: string }) => <Copy className={className} weight="duotone" />,
  CaretLeft: ({ className = "w-4 h-4" }: { className?: string }) => <CaretLeft className={className} weight="bold" />,
  CaretRight: ({ className = "w-4 h-4" }: { className?: string }) => <CaretRight className={className} weight="bold" />,
  Sidebar: ({ className = "w-5 h-5" }: { className?: string }) => <SidebarSimple className={className} weight="duotone" />,
  PieChart: ({ className = "w-5 h-5" }: { className?: string }) => <ChartPie className={className} weight="duotone" />,
  Sun: ({ className = "w-5 h-5" }: { className?: string }) => <Sun className={className} weight="bold" />,
  Moon: ({ className = "w-5 h-5" }: { className?: string }) => <Moon className={className} weight="bold" />
};
